server:
  port: 9090
  context-path: /springboot

boy:
  name: jingmiao
  age: 29
  content: content:${name},age:${age}

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dbgirl?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: root
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    cache: false

  jpa:
    hibernate:
      ddl-auto: create
      show-sql: true
